name: infobits_interactive_image
description: A simple package to to some interactive image things
version: 0.0.1
homepage: "https://infobits.dk"

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^5.2.0
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
